# Generated by Django 2.1.7 on 2019-06-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='prefer_genre',
            field=models.ManyToManyField(blank=True, related_name='prefer_user_set', to='music.Genre'),
        ),
    ]
