# Generated by Django 2.1.7 on 2019-05-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='singer',
            field=models.ManyToManyField(to='music.Singer'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(related_name='song_set', to='music.Genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='user_group',
            field=models.ManyToManyField(related_name='song_set', to='account.UserGroup'),
        ),
    ]
