# Generated by Django 2.1.7 on 2019-05-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190520_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='song_set', to='music.Genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='user_group',
            field=models.ManyToManyField(blank=True, null=True, related_name='song_set', to='account.UserGroup'),
        ),
    ]
