dist: xenial   # required for Python >= 3.7
language: python
python: "3.7"

notifications:
  email: false

sudo: required

before_install:
  - sudo python3 -m pip install -r requirements.txt

script:
  - python3 ./manage.py test
