dist: xenial   # required for Python >= 3.7
language: python
python: "3.7"

notifications:
  email: false

sudo: false

before_install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install codecov
  - pip3 install coverage

script:
  - coverage run --omit="venv/*",*migrations*,tests.py,__init__.py python3 ./manage.py test

after_success:
  - codecov
